# Generated by Django 5.1.5 on 2025-03-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='recurring_transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_recurring',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('shopping', 'Shopping'), ('transportation', 'Transportation'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('housing', 'Housing'), ('medical', 'Medical'), ('investment', 'Investment'), ('other', 'Other')], max_length=50),
        ),
        migrations.DeleteModel(
            name='RecurringTransaction',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
