# Generated by Django 5.1.5 on 2025-03-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_currency_currency_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'name', 'is_income')},
        ),
    ]
