# Generated by Django 5.1.5 on 2025-03-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_income',
            field=models.BooleanField(default=False),
        ),
    ]
