# Generated by Django 5.1.5 on 2025-03-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(condition=models.Q(('user', None)), fields=('currency_code',), name='unique_system_currency'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(condition=models.Q(('user', None), _negated=True), fields=('user', 'currency_code'), name='unique_user_currency'),
        ),
    ]
