# Generated by Django 5.1.5 on 2025-03-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card')], max_length=50),
        ),
    ]
