# Generated by Django 5.1.5 on 2025-03-15 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_account_account_type'),
    ]

    operations = [
    ]
