# Generated by Django 5.1.6 on 2025-03-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_system_default',
            field=models.BooleanField(default=False),
        ),
    ]
