# Generated by Django 5.1.5 on 2025-03-16 00:57

from django.db import migrations

def assign_users_to_categories(apps, schema_editor):
    Category = apps.get_model('finance', 'Category')
    User = apps.get_model('finance', 'User')
    
    default_user = User.objects.first()
    if default_user:
        for category in Category.objects.all():
            category.user = default_user
            category.save()

def reverse_func(apps, schema_editor):
    # This migration is irreversible
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('finance', '0008_category_user'),  
    ]

    operations = [
        migrations.RunPython(assign_users_to_categories, reverse_func),
    ]