# Generated by Django 5.1.6 on 2025-03-20 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_category_is_system_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_system_default',
        ),
    ]
