# Generated by Django 5.1.5 on 2025-03-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_assign_users_to_categories'),
    ]

    operations = [
    ]
