# Generated by Django 5.1.5 on 2025-03-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_assign_users_to_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='account',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
